apiVersion: v1
kind: Service
metadata:
  name: spacefractions-game-service
  namespace: spacefractions
  labels:
    app: spacefractions
    component: game
spec:
  type: ClusterIP
  selector:
    app: spacefractions
    component: game
  ports:
    - name: http
      port: 80
      targetPort: 3001
      protocol: TCP
    - name: metrics
      port: 9090
      targetPort: 9090
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: spacefractions-game-headless
  namespace: spacefractions
  labels:
    app: spacefractions
    component: game
spec:
  clusterIP: None
  selector:
    app: spacefractions
    component: game
